package br.com.marcelocesar.WorkFlowJavaSpring.controller;

import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.google.gson.Gson;

import br.com.marcelocesar.WorkFlowJavaSpring.drawflow.Flow;

@RestController
@RequestMapping("/redesSociais")
public class TesteFluxoController {
	
	@PostMapping("/executar")
	public void executarRedesSociais() {
		Gson gson = new Gson();
		Flow fromJson = gson.fromJson("{ "
				+ "  \"drawflow\": { "
				+ "    \"Home\": { "
				+ "      \"data\": { "
				+ "        \"1\": { "
				+ "          \"id\": 1, "
				+ "          \"name\": \"welcome\", "
				+ "          \"data\": {}, "
				+ "          \"class\": \"welcome\", "
				+ "          \"html\": \"\\n    \\n\\n      \\n👏 Welcome!!\\n\\n      \\n\\n        \\nSimple flow library demo\\n        Drawflow by Jero Soler\\n\\n\\n\\n\\n        \\nMultiple input / outputs\\n\\n           Data sync nodes\\n\\n           Import / export\\n\\n           Modules support\\n\\n           Simple use\\n\\n           Type: Fixed or Edit\\n\\n           Events: view console\\n\\n           Pure Javascript\\n\\n        \\n\\n\\n        \\n\\n        \\nShortkeys:\\n\\n\\n        \\n🎹 Delete for remove selected\\n\\n        💠 Mouse Left Click == Move\\n\\n        ❌ Mouse Right == Delete Option\\n\\n        🔍 Ctrl + Wheel == Zoom\\n\\n        📱 Mobile support\\n\\n        ...\\n\\n\\n      \\n\\n    \\n\\n    \", "
				+ "          \"typenode\": false, "
				+ "          \"inputs\": {}, "
				+ "          \"outputs\": {}, "
				+ "          \"pos_x\": 50, "
				+ "          \"pos_y\": 50 "
				+ "        }, "
				+ "        \"2\": { "
				+ "          \"id\": 2, "
				+ "          \"name\": \"slack\", "
				+ "          \"data\": {}, "
				+ "          \"class\": \"slack\", "
				+ "          \"html\": \"\\n          \\r\\n\\n            \\r\\n Slack chat message\\r\\n\\n          \\r\\n\\n          \", "
				+ "          \"typenode\": false, "
				+ "          \"inputs\": { "
				+ "            \"input_1\": { "
				+ "              \"connections\": [ "
				+ "                { "
				+ "                  \"node\": \"7\", "
				+ "                  \"input\": \"output_1\" "
				+ "                } "
				+ "              ] "
				+ "            } "
				+ "          }, "
				+ "          \"outputs\": {}, "
				+ "          \"pos_x\": 1028, "
				+ "          \"pos_y\": 87 "
				+ "        }, "
				+ "        \"3\": { "
				+ "          \"id\": 3, "
				+ "          \"name\": \"telegram\", "
				+ "          \"data\": { "
				+ "            \"channel\": \"channel_2\" "
				+ "          }, "
				+ "          \"class\": \"telegram\", "
				+ "          \"html\": \"\\n          \\r\\n\\n            \\r\\n Telegram bot\\r\\n\\n            \\r\\n\\n              \\r\\nSend to telegram\\r\\n\\r\\n\\n              \\r\\nselect channel\\r\\n\\r\\n\\n              \\r\\nChannel 1\\r\\n\\n            \\r\\n\\n          \\r\\n\\n          \", "
				+ "          \"typenode\": false, "
				+ "          \"inputs\": { "
				+ "            \"input_1\": { "
				+ "              \"connections\": [ "
				+ "                { "
				+ "                  \"node\": \"7\", "
				+ "                  \"input\": \"output_1\" "
				+ "                } "
				+ "              ] "
				+ "            } "
				+ "          }, "
				+ "          \"outputs\": {}, "
				+ "          \"pos_x\": 1032, "
				+ "          \"pos_y\": 184 "
				+ "        }, "
				+ "        \"4\": { "
				+ "          \"id\": 4, "
				+ "          \"name\": \"email\", "
				+ "          \"data\": {}, "
				+ "          \"class\": \"email\", "
				+ "          \"html\": \"\\n            \\n\\n              \\n Send Email \\n\\n            \\n\\n            \", "
				+ "          \"typenode\": false, "
				+ "          \"inputs\": { "
				+ "            \"input_1\": { "
				+ "              \"connections\": [ "
				+ "                { "
				+ "                  \"node\": \"5\", "
				+ "                  \"input\": \"output_1\" "
				+ "                } "
				+ "              ] "
				+ "            } "
				+ "          }, "
				+ "          \"outputs\": {}, "
				+ "          \"pos_x\": 1033, "
				+ "          \"pos_y\": 439 "
				+ "        }, "
				+ "        \"5\": { "
				+ "          \"id\": 5, "
				+ "          \"name\": \"template\", "
				+ "          \"data\": { "
				+ "            \"template\": \"Write your template\" "
				+ "          }, "
				+ "          \"class\": \"template\", "
				+ "          \"html\": \"\\n            \\r\\n\\n              \\r\\n Template\\r\\n\\n              \\r\\n\\n                Ger Vars\\n                \\r\\n\\n                Output template with vars\\n              \\r\\n\\n            \\r\\n\\n            \", "
				+ "          \"typenode\": false, "
				+ "          \"inputs\": { "
				+ "            \"input_1\": { "
				+ "              \"connections\": [ "
				+ "                { "
				+ "                  \"node\": \"6\", "
				+ "                  \"input\": \"output_1\" "
				+ "                } "
				+ "              ] "
				+ "            } "
				+ "          }, "
				+ "          \"outputs\": { "
				+ "            \"output_1\": { "
				+ "              \"connections\": [ "
				+ "                { "
				+ "                  \"node\": \"4\", "
				+ "                  \"output\": \"input_1\" "
				+ "                }, "
				+ "                { "
				+ "                  \"node\": \"11\", "
				+ "                  \"output\": \"input_1\" "
				+ "                } "
				+ "              ] "
				+ "            } "
				+ "          }, "
				+ "          \"pos_x\": 607, "
				+ "          \"pos_y\": 304 "
				+ "        }, "
				+ "        \"6\": { "
				+ "          \"id\": 6, "
				+ "          \"name\": \"github\", "
				+ "          \"data\": { "
				+ "            \"name\": \"https://github.com/jerosoler/Drawflow\" "
				+ "          }, "
				+ "          \"class\": \"github\", "
				+ "          \"html\": \"\\n          \\r\\n\\n            \\r\\n Github Stars\\r\\n\\n            \\r\\n\\n              \\r\\nEnter repository url\\r\\n\\r\\n\\n            \\r\\n\\n            \\r\\n\\n          \\r\\n\\n          \", "
				+ "          \"typenode\": false, "
				+ "          \"inputs\": {}, "
				+ "          \"outputs\": { "
				+ "            \"output_1\": { "
				+ "              \"connections\": [ "
				+ "                { "
				+ "                  \"node\": \"5\", "
				+ "                  \"output\": \"input_1\" "
				+ "                } "
				+ "              ] "
				+ "            } "
				+ "          }, "
				+ "          \"pos_x\": 341, "
				+ "          \"pos_y\": 191 "
				+ "        }, "
				+ "        \"7\": { "
				+ "          \"id\": 7, "
				+ "          \"name\": \"facebook\", "
				+ "          \"data\": {}, "
				+ "          \"class\": \"facebook\", "
				+ "          \"html\": \"\\n        \\r\\n\\n          \\r\\n Facebook Message\\r\\n\\n        \\r\\n\\n        \", "
				+ "          \"typenode\": false, "
				+ "          \"inputs\": {}, "
				+ "          \"outputs\": { "
				+ "            \"output_1\": { "
				+ "              \"connections\": [ "
				+ "                { "
				+ "                  \"node\": \"2\", "
				+ "                  \"output\": \"input_1\" "
				+ "                }, "
				+ "                { "
				+ "                  \"node\": \"3\", "
				+ "                  \"output\": \"input_1\" "
				+ "                }, "
				+ "                { "
				+ "                  \"node\": \"11\", "
				+ "                  \"output\": \"input_1\" "
				+ "                } "
				+ "              ] "
				+ "            } "
				+ "          }, "
				+ "          \"pos_x\": 363, "
				+ "          \"pos_y\": 53 "
				+ "        }, "
				+ "        \"11\": { "
				+ "          \"id\": 11, "
				+ "          \"name\": \"log\", "
				+ "          \"data\": {}, "
				+ "          \"class\": \"log\", "
				+ "          \"html\": \"\\n            \\r\\n\\n              \\r\\n Save log file \\r\\n\\n            \\r\\n\\n            \", "
				+ "          \"typenode\": false, "
				+ "          \"inputs\": { "
				+ "            \"input_1\": { "
				+ "              \"connections\": [ "
				+ "                { "
				+ "                  \"node\": \"5\", "
				+ "                  \"input\": \"output_1\" "
				+ "                }, "
				+ "                { "
				+ "                  \"node\": \"7\", "
				+ "                  \"input\": \"output_1\" "
				+ "                } "
				+ "              ] "
				+ "            } "
				+ "          }, "
				+ "          \"outputs\": {}, "
				+ "          \"pos_x\": 1031, "
				+ "          \"pos_y\": 363 "
				+ "        } "
				+ "      } "
				+ "    }, "
				+ "    \"Other\": { "
				+ "      \"data\": { "
				+ "        \"8\": { "
				+ "          \"id\": 8, "
				+ "          \"name\": \"personalized\", "
				+ "          \"data\": {}, "
				+ "          \"class\": \"personalized\", "
				+ "          \"html\": \"\\n            \\r\\n\\n              Personalized\\n            \\r\\n\\n            \", "
				+ "          \"typenode\": false, "
				+ "          \"inputs\": { "
				+ "            \"input_1\": { "
				+ "              \"connections\": [ "
				+ "                { "
				+ "                  \"node\": \"12\", "
				+ "                  \"input\": \"output_1\" "
				+ "                }, "
				+ "                { "
				+ "                  \"node\": \"12\", "
				+ "                  \"input\": \"output_2\" "
				+ "                }, "
				+ "                { "
				+ "                  \"node\": \"12\", "
				+ "                  \"input\": \"output_3\" "
				+ "                }, "
				+ "                { "
				+ "                  \"node\": \"12\", "
				+ "                  \"input\": \"output_4\" "
				+ "                } "
				+ "              ] "
				+ "            } "
				+ "          }, "
				+ "          \"outputs\": { "
				+ "            \"output_1\": { "
				+ "              \"connections\": [ "
				+ "                { "
				+ "                  \"node\": \"9\", "
				+ "                  \"output\": \"input_1\" "
				+ "                } "
				+ "              ] "
				+ "            } "
				+ "          }, "
				+ "          \"pos_x\": 764, "
				+ "          \"pos_y\": 227 "
				+ "        }, "
				+ "        \"9\": { "
				+ "          \"id\": 9, "
				+ "          \"name\": \"dbclick\", "
				+ "          \"data\": { "
				+ "            \"name\": \"Hello World!!\" "
				+ "          }, "
				+ "          \"class\": \"dbclick\", "
				+ "          \"html\": \"\\n            \\r\\n\\n            \\r\\n Db Click\\r\\n\\n              \\r\\n\\n                Db Click here\\n                \\r\\n\\n                  \\r\\n\\n                    ×\\n                    Change your variable {name} !\\n                    \\r\\n\\n                  \\r\\n\\n\\n                \\r\\n\\n              \\r\\n\\n            \\r\\n\\n            \", "
				+ "          \"typenode\": false, "
				+ "          \"inputs\": { "
				+ "            \"input_1\": { "
				+ "              \"connections\": [ "
				+ "                { "
				+ "                  \"node\": \"8\", "
				+ "                  \"input\": \"output_1\" "
				+ "                } "
				+ "              ] "
				+ "            } "
				+ "          }, "
				+ "          \"outputs\": { "
				+ "            \"output_1\": { "
				+ "              \"connections\": [ "
				+ "                { "
				+ "                  \"node\": \"12\", "
				+ "                  \"output\": \"input_2\" "
				+ "                } "
				+ "              ] "
				+ "            } "
				+ "          }, "
				+ "          \"pos_x\": 209, "
				+ "          \"pos_y\": 38 "
				+ "        }, "
				+ "        \"12\": { "
				+ "          \"id\": 12, "
				+ "          \"name\": \"multiple\", "
				+ "          \"data\": {}, "
				+ "          \"class\": \"multiple\", "
				+ "          \"html\": \"\\n            \\r\\n\\n              \\r\\n\\n                Multiple!\\n              \\r\\n\\n            \\r\\n\\n            \", "
				+ "          \"typenode\": false, "
				+ "          \"inputs\": { "
				+ "            \"input_1\": { "
				+ "              \"connections\": [] "
				+ "            }, "
				+ "            \"input_2\": { "
				+ "              \"connections\": [ "
				+ "                { "
				+ "                  \"node\": \"9\", "
				+ "                  \"input\": \"output_1\" "
				+ "                } "
				+ "              ] "
				+ "            }, "
				+ "            \"input_3\": { "
				+ "              \"connections\": [] "
				+ "            } "
				+ "          }, "
				+ "          \"outputs\": { "
				+ "            \"output_1\": { "
				+ "              \"connections\": [ "
				+ "                { "
				+ "                  \"node\": \"8\", "
				+ "                  \"output\": \"input_1\" "
				+ "                } "
				+ "              ] "
				+ "            }, "
				+ "            \"output_2\": { "
				+ "              \"connections\": [ "
				+ "                { "
				+ "                  \"node\": \"8\", "
				+ "                  \"output\": \"input_1\" "
				+ "                } "
				+ "              ] "
				+ "            }, "
				+ "            \"output_3\": { "
				+ "              \"connections\": [ "
				+ "                { "
				+ "                  \"node\": \"8\", "
				+ "                  \"output\": \"input_1\" "
				+ "                } "
				+ "              ] "
				+ "            }, "
				+ "            \"output_4\": { "
				+ "              \"connections\": [ "
				+ "                { "
				+ "                  \"node\": \"8\", "
				+ "                  \"output\": \"input_1\" "
				+ "                } "
				+ "              ] "
				+ "            } "
				+ "          }, "
				+ "          \"pos_x\": 179, "
				+ "          \"pos_y\": 272 "
				+ "        } "
				+ "      } "
				+ "    } "
				+ "  } "
				+ "}", Flow.class);
		System.out.println(new Gson().toJson(fromJson));
	}
}
